settings:
  title: '站点检测'
  url: 'https://status.666986.xyz' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有站点正常访问'
  notAllmonitorsOperational: '部分站点正常访问'
  monitorLabelOperational: '正常运行'
  monitorLabelNotOperational: '发生故障'
  monitorLabelNoData: '暂无数据'
  dayInHistogramNoData: '暂无数据'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: self-nav-page # unique identifier
    name: '导航面板监控'
    description: '导航面板' # default=empty
    url: 'https://nav.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: self-nezha-page # unique identifier
    name: '探针'
    description: '探针' # default=empty
    url: 'http://ly.565869.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: self-music-page # unique identifier
    name: '音乐独享'
    description: '音乐独享' # default=empty
    url: 'http://159.75.70.243/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
