settings:
  title: '站点检测'
  url: 'https://status.666986.xyz' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有站点正常访问'
  notAllmonitorsOperational: '部分站点正常访问'
  monitorLabelOperational: '正常运行'
  monitorLabelNotOperational: '发生故障'
  monitorLabelNoData: '暂无数据'
  dayInHistogramNoData: '暂无数据'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
 
  - id: self-air-page # unique identifier
    name: '机场'
    description: '机场面板' # default=empty
    url: 'https://airport.oracleusa.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-nav-page # unique identifier
    name: '导航面板监控'
    description: '导航面板' # default=empty
    url: 'https://nav.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-clash-page # unique identifier
    name: '订阅转换'
    description: '订阅转换' # default=empty
    url: 'https://clash.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-daili-page # unique identifier
    name: '公益代理池'
    description: '公益代理池' # default=empty
    url: 'https://bt.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
   
  - id: self-pan-page # unique identifier
    name: '个人网盘'
    description: '个人网盘' # default=empty
    url: 'http://rk.565869.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
   
  - id: self-nezha-page # unique identifier
    name: '阅读'
    description: '阅读' # default=empty
    url: 'https://www.565869.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
  
  - id: self-blog-page # unique identifier
    name: '个人博客'
    description: '个人博客' # default=empty
    url: 'https://ly.565869.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
        
  - id: self-short-page # unique identifier
    name: '短链接'
    description: '短链接' # default=empty
    url: 'https://xg.565869.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
  

