settings:
  title: '站点检测'
  url: 'https://status.mistyhill.ml' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有站点正常访问'
  notAllmonitorsOperational: '部分站点正常访问'
  monitorLabelOperational: '正常运行'
  monitorLabelNotOperational: '发生故障'
  monitorLabelNoData: '暂无数据'
  dayInHistogramNoData: '暂无数据'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: self-nav-page # unique identifier
    name: '监控 - 导航面板'
    description: '导航面板' # default=empty
    url: 'https://nav.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-clash-page # unique identifier
    name: '监控 - 订阅转换'
    description: '订阅转换' # default=empty
    url: 'https://sub.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-nav-page # unique identifier
    name: '监控 - 诺星导航'
    description: '诺星导航' # default=empty
    url: 'https://notion-nav.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-blog-page # unique identifier
    name: '监控 - 个人博客'
    description: '个人博客' # default=empty
    url: 'https://notion-blog.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: cloud-daili-page # unique identifier
    name: '监控 - 订阅托管'
    description: '订阅托管' # default=empty
    url: 'https://share.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: cloud-short-page # unique identifier
    name: '监控 - 短链接'
    description: '短链接' # default=empty
    url: 'https://s.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: cloud-air-page # unique identifier
    name: '监控 - 浏览器'
    description: '浏览器' # default=empty
    url: 'https://s.sob.im/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
   
  - id: cloud-pan-page # unique identifier
    name: '监控 - 个人网盘'
    description: '个人网盘' # default=empty
    url: 'https://list.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
  
  - id: cloud-pan-page # unique identifier
    name: '监控 - 阿里网盘'
    description: '阿里网盘' # default=empty
    url: 'https://pan.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
   
  - id: self-kuma-page # unique identifier
    name: '监控 - kuma'
    description: 'kuma' # default=empty
    url: 'https://kuma.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-nezha-page # unique identifier
    name: '监控 - nezha'
    description: 'nezha' # default=empty
    url: 'https://nezha.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: self-probe-page # unique identifier
    name: '监控 - probe'
    description: 'probe' # default=empty
    url: 'https://probe.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: self-reader-page # unique identifier
    name: '监控 - 阅读'
    description: '阅读' # default=empty
    url: 'https://reader.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
  
  - id: self-panindex-page # unique identifier
    name: '监控 - panindex'
    description: 'panindex' # default=empty
    url: 'https://disk.mistyhill.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

      
  

