settings:
  title: '稳定站点 在线检测'
  url: 'https://status.666986.xyz' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有站点正常访问'
  notAllmonitorsOperational: '部分站点正常访问'
  monitorLabelOperational: '正常运行'
  monitorLabelNotOperational: '发生故障'
  monitorLabelNoData: '暂无数据'
  dayInHistogramNoData: '暂无数据'
  dayInHistogramOperational: '全部正常'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: self-nav-page # unique identifier
    name: '云服务 - cf - 导航面板'
    description: '导航面板' # default=empty
    url: 'https://nav.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-clash-page # unique identifier
    name: '云服务 - netlify - sub'
    description: '订阅转换' # default=empty
    url: 'https://sub.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
  
  - id: self-clash-suber # unique identifier
    name: '云服务 - netlify - suber'
    description: 'Sub Store' # default=empty
    url: 'https://suber.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-clash-box # unique identifier
    name: '云服务 - netlify - box'
    description: 'BoxJS' # default=empty
    url: 'https://box.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-notionnav-page # unique identifier
    name: '云服务 - vercel - 诺星导航'
    description: '诺星导航' # default=empty
    url: 'https://notion-nav.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-notionblog-page # unique identifier
    name: '云服务 - vercel - 诺星博客'
    description: '诺星博客' # default=empty
    url: 'https://notion-blog.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-panindex-page # unique identifier
    name: '云服务 - vercel - 网盘TGSTORE'
    description: '网盘TGSTORE' # default=empty
    url: 'https://tgs.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-bdpcs-page # unique identifier
    name: '云服务 - cf - 网盘bdpcs'
    description: '网盘bdpcs' # default=empty
    url: 'https://bdpcs.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-githubblog-page # unique identifier
    name: '云服务 - github - 托管博客'
    description: '托管博客' # default=empty
    url: 'https://blog.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-githubblog-page # unique identifier
    name: '云服务 - vercel - 啤酒屋'
    description: '啤酒屋' # default=empty
    url: 'https://talk.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: self-githubblog-page # unique identifier
    name: '云服务 - vercel - BIO'
    description: 'BIO' # default=empty
    url: 'https://bio.666986.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
